name: CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          config-file: cypress-ci.json
